global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  # Prometheus self-scrape
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Your backend service
  - job_name: 'audiojot-service'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - 'audiojot-service.railway.internal:80'